import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Layer, Rect, Ellipse } from 'react-konva';

const Roads = (props) => {

    return (
        <Layer>
            {/* row one */}
            <Ellipse
                x={225}
                y={107.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={275}
                y={107.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={325}
                y={107.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={375}
                y={107.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={425}
                y={107.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={475}
                y={107.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row two */}
            <Ellipse
                x={200}
                y={150}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={300}
                y={150}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={400}
                y={150}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={500}
                y={150}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row three */}
            <Ellipse
                x={225}
                y={192.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={175}
                y={192.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={325}
                y={192.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={275}
                y={192.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={425}
                y={192.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={375}
                y={192.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={525}
                y={192.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={475}
                y={192.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row four */}
            <Ellipse
                x={150}
                y={235}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={250}
                y={235}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={350}
                y={235}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={450}
                y={235}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={550}
                y={235}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row five */}
            <Ellipse
                x={125}
                y={277.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={175}
                y={277.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={225}
                y={277.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={275}
                y={277.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={325}
                y={277.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={375}
                y={277.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={425}
                y={277.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={475}
                y={277.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={525}
                y={277.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={575}
                y={277.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row six */}
            <Ellipse
                x={100}
                y={320}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={200}
                y={320}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={300}
                y={320}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={400}
                y={320}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={500}
                y={320}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={600}
                y={320}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row seven */}
            <Ellipse
                x={125}
                y={362.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={175}
                y={362.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={225}
                y={362.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={275}
                y={362.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={325}
                y={362.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={375}
                y={362.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={425}
                y={362.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={475}
                y={362.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={525}
                y={362.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={575}
                y={362.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row eight */}
            <Ellipse
                x={150}
                y={405}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={250}
                y={405}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={350}
                y={405}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={450}
                y={405}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={550}
                y={405}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row nine */}
            <Ellipse
                x={175}
                y={447.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={225}
                y={447.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={275}
                y={447.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={325}
                y={447.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={375}
                y={447.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={425}
                y={447.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={475}
                y={447.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={525}
                y={447.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row ten */}
            <Ellipse
                x={200}
                y={490}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={300}
                y={490}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={400}
                y={490}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={500}
                y={490}
                width={10}
                height={35}
                fill={'red'}
                shadowBlur={5}
            />

            {/* row eleven */}
            <Ellipse
                x={225}
                y={532.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={275}
                y={532.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={325}
                y={532.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={375}
                y={532.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={425}
                y={532.5}
                width={10}
                height={35}
                rotation={-60}
                fill={'red'}
                shadowBlur={5}
            />
            <Ellipse
                x={475}
                y={532.5}
                width={10}
                height={35}
                rotation={60}
                fill={'red'}
                shadowBlur={5}
            />

        </Layer>
    );
};

export default Roads;
